[package]
name = "rust_voxel_engine"
version = "0.1.0"
authors = ["pannoire <maciekolej@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.34.0", features = ["bundled", "static-link"] }
gl = { path = "lib/gl" }
glm = "0.2.3"
stb_image = "0.2.2"